name: Bug Report
description: Something is wrong!
type: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before continuing to make the issue, please make sure there are no similar issues on [the issue tracker](https://github.com/weightedangelcube/slime-origin/issues). If there are, consider contributing your information in there instead!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: 'Also tell us, what did you expect to happen? Please provide some reproduction steps: What did you do to trigger the bug?'
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can add images by clicking on the button in the bar that will appear once you click this textbox.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: 'Please upload a client log file by dragging and dropping it into this section. Usually this is found at `.minecraft/logs/latest.log`. If you are not sure how to find `.minecraft`, please see this article: https://minecraft.wiki/w/.minecraft#Locating_.minecraft. Please do not upload a compressed (`.log.gz`) file, they are very difficult for us to read when viewing issue reports. The log file instantly tells us important information like the versions of any other installed mods or if there are errors so it is very very important that you include it in your report.'
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: 'Add any other context about the problem here. If you are proficient at reading log files and think there is an especially relevant section, feel free to paste it in a code block here - that is not required, though.'
    validations:
      required: false
